services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/code-challenges
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - DOCKER_MEMORY_LIMIT=128m
      - DOCKER_CPU_QUOTA=100000
      - DOCKER_TIMEOUT=10000
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
    depends_on:
      - mongodb
    command: npm run dev

  code-runner:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - VITE_GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
    depends_on:
      - backend
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
